name: Chris Sisk
favicon: null
layout_spectrum: 0.7291636085137725
typography_spectrum: 0.07713238405995071
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3790738263633102
  lightness: 0.563653748948127
  saturation: 0.5799857890233397
  rhythmicContrast: 0.9729721918702126
purpose: []
